version: 2

sphinx:
  configuration: docs/conf.py  # Path to your conf.py file

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt  # Your requirements file

formats:
  - htmlzip

# This section tells Read the Docs to use extensions
sphinx:
  # Specify any extensions you need
  extra_extensions:
    - sphinx_markdown_docs  # Ensure this is valid and correctly installed in your requirements
