# .readthedocs.yml

version: 2

# Build documentation in the "docs/" directory
sphinx:
  configuration: docs/source/conf.py  # Path to your Sphinx conf.py file

# Install dependencies
python:
  install:
    - requirements: requirements.txt
